# Generated by Django 4.1.1 on 2022-10-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('weigth_product', models.FloatField()),
                ('pricekg', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
