# Generated by Django 4.1.1 on 2022-11-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productone_delete_product'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='product.productone'),
        ),
        migrations.AlterField(
            model_name='food',
            name='weigth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weigth', to='product.productone'),
        ),
    ]
