# Generated by Django 4.1.3 on 2022-11-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productone_delete_product'),
        ('food', '0003_remove_food_price_food_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredient3',
            field=models.ManyToManyField(null=True, related_name='ingredient3', to='product.productone'),
        ),
    ]
