# Generated by Django 4.1.3 on 2022-11-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_foodfull_delete_fullfood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodFull',
        ),
    ]
