# Generated by Django 4.1.3 on 2022-11-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productone_delete_product'),
        ('food', '0008_remove_food_ingredient3_remove_food_weigth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='product.productone')),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredient',
            field=models.ManyToManyField(null=True, related_name='food_ingredient', to='food.foodingredient'),
        ),
    ]
