# Generated by Django 4.0.4 on 2022-11-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productone_delete_product'),
        ('food', '0010_remove_food_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodingredient',
            name='ingredient_one',
        ),
        migrations.AddField(
            model_name='foodingredient',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_one', to='product.productone'),
        ),
    ]
