# Generated by Django 4.0.4 on 2022-11-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_remove_foodingredient_ingredient_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodingredient',
            name='countfood',
            field=models.IntegerField(null=True),
        ),
    ]
