# Generated by Django 4.0.4 on 2022-11-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_foodingredient_countfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodingredient',
            name='countfood',
        ),
        migrations.AddField(
            model_name='food',
            name='countfood',
            field=models.IntegerField(null=True),
        ),
    ]
