# Generated by Django 4.1.1 on 2022-11-12 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productone_delete_product'),
        ('food', '0013_remove_foodingredient_countfood_food_countfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productone')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodIngredient',
        ),
    ]
