# Generated by Django 4.1.1 on 2022-11-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_recipe_delete_foodingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
