# Generated by Django 4.1.1 on 2022-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_alter_recipe_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='need',
            field=models.IntegerField(null=True),
        ),
    ]
