# Generated by Django 4.1.1 on 2022-11-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_recipe_need'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='score',
            new_name='ingredient_name',
        ),
    ]
