# Generated by Django 4.1.1 on 2022-11-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_rename_score_recipe_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='need',
            field=models.FloatField(null=True),
        ),
    ]
