# Generated by Django 4.1.1 on 2022-11-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_alter_recipe_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='countfood',
            field=models.FloatField(null=True),
        ),
    ]
