# Generated by Django 4.1.1 on 2022-11-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_food_price_alter_food_countfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time_relise',
            field=models.IntegerField(null=True),
        ),
    ]
